### PR TITLE
unit tests for Project end point and few tiny fixes

### PR DESCRIPTION
**Pull request by grillazz**
This change is [Reviewable](https://reviewable.io/reviews/enviromonitor/enviromonitorweb/40)

### CODE REVIEW

**Comment by lechup** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[api/tests/factories.py, line 14 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40#-KbL74scUSzeiLlY7PCF:-KbL74scUSzeiLlY7PCG:bp4wlpy) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/479ad5e0e97e68600df2c627bcac30006ca9d901/api/tests/factories.py#L14)):*
> ```Python
> # http://stackoverflow.com/questions/24748222/django-python-django-login-test-failed-with-factory-boy-and-authtools
> user_password = 'very_dangerous_password'
> ```

Can we keep it under `UserFactory.DEFAULT_PASSWORD` ?

---

*[api/tests/factories.py, line 57 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40#-KbL2Y2623C2mSv6_8U4:-KbL2Y2623C2mSv6_8U5:bx4eh6z) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/479ad5e0e97e68600df2c627bcac30006ca9d901/api/tests/factories.py#L57)):*
> ```Python
> 
> 
> # factory to deliver data valid for project endpoint
> ```

Why do we need second `ProjectFactory`? I guess I'm missing something...

---

*[api/tests/test_views.py, line 14 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40#-KbL3H_tZhxaith0fpy6:-KbL3H_tZhxaith0fpy7:ba1r34i) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/479ad5e0e97e68600df2c627bcac30006ca9d901/api/tests/test_views.py#L14)):*
> ```Python
>         self.api_data = factory_build(dict, FACTORY_CLASS=ProjectFactoryForTesting)
>         self.api_url = reverse('project-list')
>         self.user_factory = UserFactory()
> ```

I would call the variable `user` or `test_user`.  Is `*_factory` convention I'm not aware of?

---

*[api/tests/test_views.py, line 22 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40#-KbL4AETImYV-gItCCKZ:-KbL4AETImYV-gItCCK_:bqrkb8t) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/479ad5e0e97e68600df2c627bcac30006ca9d901/api/tests/test_views.py#L22)):*
> ```Python
>         self.assertEqual(Project.objects.count(), 1)
>         self.assertEqual(Project.objects.get().name, self.api_data['name'])
> ```

Generally those tests are correct, we do need some more cases like:
* checking that all proper fields are in responses not only `name`
* unauthorized write access - fail
* unauthorized read access - ok

Of course it can be next PR, maybe @marcindbar will be able to write some of them...

---

*[EnviroMonitorWeb/settings/test.py, line 3 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40#-KbL5FqzS2gC2qIUPy2e:-KbL5FqzS2gC2qIUPy2f:bspt8cc) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/479ad5e0e97e68600df2c627bcac30006ca9d901/EnviroMonitorWeb/settings/test.py#L3)):*
> ```Python
> from .base import *
> 
> ALLOWED_HOSTS = ['*']
> ```

I think You need also change entry in `pytest.ini` from `.tests` to `.test`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40)*

**Comment by grillazz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[api/tests/factories.py, line 14 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40#-KbL74scUSzeiLlY7PCF:-KbPn-J6YqzAh9qAKt5_:bb7101v) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/479ad5e0e97e68600df2c627bcac30006ca9d901/api/tests/factories.py#L14)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

Can we keep it under `UserFactory.DEFAULT_PASSWORD` ?
</blockquote></details>

Np.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40)*

**Comment by grillazz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[api/tests/factories.py, line 57 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40#-KbL2Y2623C2mSv6_8U4:-KbPoEPRWLZaroGzekIk:bv6zrkx) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/479ad5e0e97e68600df2c627bcac30006ca9d901/api/tests/factories.py#L57)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

Why do we need second `ProjectFactory`? I guess I'm missing something...
</blockquote></details>

Well that simple if you check what fields we have in /api/v1/project/ endpoint 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40)*

**Comment by grillazz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[api/tests/test_views.py, line 14 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40#-KbL3H_tZhxaith0fpy6:-KbPoU5oxsFx9Y82e-6F:bry5d6j) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/479ad5e0e97e68600df2c627bcac30006ca9d901/api/tests/test_views.py#L14)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

I would call the variable `user` or `test_user`.  Is `*_factory` convention I'm not aware of?
</blockquote></details>

will update from user.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40)*

**Comment by grillazz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[api/tests/test_views.py, line 22 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40#-KbL4AETImYV-gItCCKZ:-KbPoaA_hcxLY3Bf3jjN:b4c7tv4) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/479ad5e0e97e68600df2c627bcac30006ca9d901/api/tests/test_views.py#L22)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

Generally those tests are correct, we do need some more cases like:
* checking that all proper fields are in responses not only `name`
* unauthorized write access - fail
* unauthorized read access - ok

Of course it can be next PR, maybe @marcindbar will be able to write some of them...
</blockquote></details>

I add above. After that we can ask @marcindbar if he want jump in and add similar test for other endpoints

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40)*

**Comment by grillazz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[EnviroMonitorWeb/settings/test.py, line 3 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40#-KbL5FqzS2gC2qIUPy2e:-KbPrtVN_MmmG8V4ezSw:b-886gsx) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/479ad5e0e97e68600df2c627bcac30006ca9d901/EnviroMonitorWeb/settings/test.py#L3)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

I think You need also change entry in `pytest.ini` from `.tests` to `.test`.
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40)*

**Comment by grillazz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[api/tests/test_views.py, line 14 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40#-KbL3H_tZhxaith0fpy6:-KbPtFowqqeVm-Oy1iWd:b-886gsx) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/479ad5e0e97e68600df2c627bcac30006ca9d901/api/tests/test_views.py#L14)):*
<details><summary><i>Previously, grillazz (Jakub Miazek) wrote…</i></summary><blockquote>

will update from user.
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40)*

**Comment by grillazz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[api/tests/factories.py, line 14 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40#-KbL74scUSzeiLlY7PCF:-KbQ1ccSDwI6TK-8rjbd:b-unndv7) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/479ad5e0e97e68600df2c627bcac30006ca9d901/api/tests/factories.py#L14)):*
<details><summary><i>Previously, grillazz (Jakub Miazek) wrote…</i></summary><blockquote>

Np.
</blockquote></details>

Sorry but I tried this approach with no luck ... so will leave it as it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40)*

**Comment by lechup** [comment]
:lgtm: I'll try to create next PR to check whether my ideas were possible ;)

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/40#-:-KbQClTTqr4kUHjvCBPu:btfh4hi)*

**Pull request merged**
