### PR TITLE
add JWT auth 

### LINKED ISSUE #11: add token auth
Hi @zen - please let me know which standard you would like to add to project. 
http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication or http://www.django-rest-framework.org/api-guide/authentication/#json-web-token-authentication ?

### PR DESCRIPTION
**Pull request by grillazz**
closes #11

---
This change is [Reviewable](https://reviewable.io/reviews/enviromonitor/enviromonitorweb/52)

### CODE REVIEW

**Comment by lechup** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[api/tests/test_views_jwt_auth.py, line 19 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/52#-KdVam8dAEZRS-PhsuTI:-KdVam8dAEZRS-PhsuTJ:b-hrxeyo) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/7cf44a7871e5528a40539fb1395d1404f4692227/api/tests/test_views_jwt_auth.py#L19)):*
> ```Python
> 
> 
> class ProjectApiTests(APITestCase):
> ```

I guess those tests should be merged with `./test_views.py`? Shouldn't we support JWT auth only?

---

*[EnviroMonitorWeb/settings/base.py, line 148 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/52#-KdVb-XQgUdKxgXgB8xJ:-KdVb-XQgUdKxgXgB8xK:b-wczqg) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/7cf44a7871e5528a40539fb1395d1404f4692227/EnviroMonitorWeb/settings/base.py#L148)):*
> ```Python
>     'DEFAULT_AUTHENTICATION_CLASSES': (
>         'rest_framework.authentication.SessionAuthentication',
>         'rest_framework.authentication.BasicAuthentication',
> ```

I would leave JWT only. Or do we need Basic and Session somewhere? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/52)*

**Comment by grillazz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[api/tests/test_views_jwt_auth.py, line 19 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/52#-KdVam8dAEZRS-PhsuTI:-KdVkoEQM8_9kq2QjRm0:b-coxdor) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/7cf44a7871e5528a40539fb1395d1404f4692227/api/tests/test_views_jwt_auth.py#L19)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

I guess those tests should be merged with `./test_views.py`? Shouldn't we support JWT auth only?
</blockquote></details>

Well. I wasn't sure about that but Im 100% ok with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/52)*

**Comment by grillazz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[EnviroMonitorWeb/settings/base.py, line 148 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/52#-KdVb-XQgUdKxgXgB8xJ:-KdVkwVJLIacJsjcOuTO:bq696ql) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/7cf44a7871e5528a40539fb1395d1404f4692227/EnviroMonitorWeb/settings/base.py#L148)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

I would leave JWT only. Or do we need Basic and Session somewhere? 
</blockquote></details>

I will merge tests and remove session auth then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/52)*

**Comment by lechup** [comment]
Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[EnviroMonitorWeb/settings/base.py, line 157 at r2](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/52#-Kdfa9WFfWeca_I4GzgW:-Kdfa9WFfWeca_I4GzgX:b-iv8bdp) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/9e4956b8877e7be20e3c25567a18169c0360b679/EnviroMonitorWeb/settings/base.py#L157)):*
> ```Python
>     'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticatedOrReadOnly',),
>     'DEFAULT_AUTHENTICATION_CLASSES': (
>         'rest_framework.authentication.BasicAuthentication',
> ```

Can we also remove BasicAuth or it is needed somewhere?

---

*[EnviroMonitorWeb/settings/dev.py, line 7 at r2](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/52#-Kdf_lxuupkUvfgyOghU:-Kdf_lxvaDks6euV4TEj:b4l426h) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/9e4956b8877e7be20e3c25567a18169c0360b679/EnviroMonitorWeb/settings/dev.py#L7)):*
> ```Python
> 
> REST_FRAMEWORK = {
>     'DEFAULT_RENDERER_CLASSES': (
> ```

I would set only on key from `REST_FRAMEWORK` dict (I spotted difference only there)

```
REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES'] = {
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/52)*

**Comment by lechup** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/52#-:-Kdz-ByDh2QZSG_VODSp:bnfp4nl)*

**Pull request merged**
