### PR TITLE
add swagger as rest api documentation

### LINKED ISSUE #3: add swagger as rest api documentation
https://github.com/marcgibbons/django-rest-swagger

### PR DESCRIPTION
**Pull request by grillazz**
This change is [Reviewable](https://reviewable.io/reviews/enviromonitor/enviromonitorweb/6)

### CODE REVIEW

**Comment by zen** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[EnviroMonitorWeb/docs/views.py, line 9 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/6#-KXwUpOk_uavItQz-yUC:-KXwUpOlCJWz4XZJKdi-:b362e2m) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/bb36458ea247a49519cc4d1ecb9b1497faaccd18/EnviroMonitorWeb/docs/views.py#L9)):*
> Saudi Matches API'
Not sure what this is, any details?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/6)*

**Comment by grillazz** [comment]
Sorry @zen. Saudi Matches is project which I just finishing. So forget to change it in this piece of code :) It is fixed now.

**Comment by ajakubo1** [comment]
@grillazz - I'll try to do the review in the evening. Oh, and I'll start working on something in the weekend :).

**Comment by ajakubo1** [comment]
:lgtm: Tested that out - swagger seems really nice! Not a lot of work to set it up, and you've got nice documentation!

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/6#-:-KY-QB4ga4B3P74dmjSo:b-obzaya)*

**Comment by ajakubo1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[EnviroMonitorWeb/docs/views.py, line 9 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/6#-KXwUpOk_uavItQz-yUC:-KY-T8T_TogXZ64u9tcy:bsj646i) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/bb36458ea247a49519cc4d1ecb9b1497faaccd18/EnviroMonitorWeb/docs/views.py#L9)):*
<details><summary><i>Previously, zen (Tomasz Napierala) wrote…</i></summary><blockquote>

> Saudi Matches API'
Not sure what this is, any details?
</blockquote></details>

Corrected.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/6)*

**Comment by ajakubo1** [comment]
Hmm, @zen, I think you should accept @grillazz solution? Should I merge the branch with pending status, or wait for your approval?

**Comment by zen** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[EnviroMonitorWeb/docs/views.py, line 9 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/6#-KXwUpOk_uavItQz-yUC:-KY-jlLAHjZe08iKJNER:b-zcjvte) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/bb36458ea247a49519cc4d1ecb9b1497faaccd18/EnviroMonitorWeb/docs/views.py#L9)):*
<details><summary><i>Previously, ajakubo1 (Adam Jakubowski) wrote…</i></summary><blockquote>

Corrected.
</blockquote></details>

Thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/6#-:-KY-jpHhcloxcxXe_2t0:bnfp4nl)*

**Comment by zen** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/6)*

**Comment by zen** [comment]
Folks, do not hesitate to merge your stuff, just try to keep simple rules:
- don't merge your own stuff
- test merges
- at least one review

Also, PR title could be little more descriptive ;)

**Comment by zen** [comment]
OK 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[EnviroMonitorWeb/docs/views.py, line 9 at r1](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/6#-KXwUpOk_uavItQz-yUC:-KY-mBtrwmg06zkTBa8N:b32w0x) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/bb36458ea247a49519cc4d1ecb9b1497faaccd18/EnviroMonitorWeb/docs/views.py#L9)):*
<details><summary><i>Previously, zen (Tomasz Napierala) wrote…</i></summary><blockquote>

Thanks
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/6#-:-KY-lmxZK1uauFvvBLvr:b2nhktb)*

**Comment by grillazz** [comment]
closes #3

**Pull request merged**
