### PR TITLE
Jakub/responsive layout

### PR DESCRIPTION
**Pull request by grillazz**
This change is [Reviewable](https://reviewable.io/reviews/enviromonitor/enviromonitorweb/10)

### CODE REVIEW

**Comment by grillazz** [comment]
@lechup here: https://reviewable.io/reviews/enviromonitor/enviromonitorweb/10

**Comment by lechup** [comment]
Hm... I don't like so many commits with same description. I'm usually using `git commit --amend` and `git push -f` in such situations. Just poiting this one for future.

Second thing, shouldn't travis and py.test related thing be on different branch?

---

Review status: 0 of 17 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/10#-:-KZQmE1Tqh2rWRtpknqi:b-nnhr06)*

**Comment by grillazz** [comment]
@lechup Dude I waited for review and received from you only "Couple new lines missing but generally ok." To me mean nothing. Question: Why you didn't  verified my PR here: https://reviewable.io/reviews/enviromonitor/enviromonitorweb/10 as we agreed at the begging ?
... so I have limited time for this project and decided to add Travis and py.test asap to close few tiny issues at once. I will wait for @zen ;) in this case

**Comment by lechup** [comment]
Just check the diff on github/reviewable and You will see new lines that are missing at the end of the files.

Ok I'll try to be the best linter ever.

PS: It's my first time I use reviewable, to be ohnest I'm quite used to github, will try my best to make reviews here.
PS2: I also have limited time but it's quite easy and fast to create branch based on master or feature branch which is waiting to review... yeah, You can call me "mr clean" vel "nitpicker".

---

Reviewed 14 of 14 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[EnviroMonitorWeb/requirements.txt, line 15 at r2](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/10#-KZRAoecuMcFjftOEAEe:-KZRAoed0Dmgj1suz-t4:b-byfdrb) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/97a44c9cdeff5292576d551e86da4e90c0d088e3/EnviroMonitorWeb/requirements.txt#L15)):*
> ```
> pytest-cov==2.4.0
> pytest-django==3.1.2
> pytest-watch==4.1.0
> ```

New line

---

*[EnviroMonitorWeb/docs/views.py, line 10 at r2](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/10#-KZRAq1buLW_mvzNGZ2e:-KZRAq1buLW_mvzNGZ2f:b-d0wxhj) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/97a44c9cdeff5292576d551e86da4e90c0d088e3/EnviroMonitorWeb/docs/views.py#L10)):*
> ```Python
> def schema_view(request):
>     generator = schemas.SchemaGenerator(title='Air Monitor REST API')
>     return response.Response(generator.get_schema(request=request))
> ```

new line

---

*[EnviroMonitorWeb/templates/rest_framework/admin.html, line 13 at r2](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/10#-KZRAtTloWs89T-BwPvD:-KZRAtTloWs89T-BwPvE:b-d0wxhj) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/97a44c9cdeff5292576d551e86da4e90c0d088e3/EnviroMonitorWeb/templates/rest_framework/admin.html#L13)):*
> ```HTML
> {#        #}
> {#    </a>#}
> {% endblock %}
> ```

new line

---

*[EnviroMonitorWeb/templates/rest_framework/api.html, line 13 at r2](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/10#-KZRAuP8e4HrYzMpx4Z1:-KZRAuP8e4HrYzMpx4Z2:b-d0wxhj) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/97a44c9cdeff5292576d551e86da4e90c0d088e3/EnviroMonitorWeb/templates/rest_framework/api.html#L13)):*
> ```HTML
> {#        #}
> {#    </a>#}
> {% endblock %}
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/10#-:-KZR9yZC3cG0pdSVmpFm:b-kblugg)*

**Comment by grillazz** [comment]
Review status: 11 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[EnviroMonitorWeb/requirements.txt, line 15 at r2](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/10#-KZRAoecuMcFjftOEAEe:-KZVSKn-TmqbcOPaTws6:b-qssecl) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/97a44c9cdeff5292576d551e86da4e90c0d088e3/EnviroMonitorWeb/requirements.txt#L15)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

New line
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/10)*

**Comment by grillazz** [comment]
Review status: 11 of 18 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[EnviroMonitorWeb/docs/views.py, line 10 at r2](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/10#-KZRAq1buLW_mvzNGZ2e:-KZVVf5-eG2KNjjFcUR4:b-896fix) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/97a44c9cdeff5292576d551e86da4e90c0d088e3/EnviroMonitorWeb/docs/views.py#L10)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[EnviroMonitorWeb/templates/rest_framework/admin.html, line 13 at r2](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/10#-KZRAtTloWs89T-BwPvD:-KZVViHsfVkZ8kNvmQH3:b-896fix) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/97a44c9cdeff5292576d551e86da4e90c0d088e3/EnviroMonitorWeb/templates/rest_framework/admin.html#L13)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[EnviroMonitorWeb/templates/rest_framework/api.html, line 13 at r2](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/10#-KZRAuP8e4HrYzMpx4Z1:-KZVVinckJXMB6FtaLNr:b-896fix) ([raw file](https://github.com/enviromonitor/enviromonitorweb/blob/97a44c9cdeff5292576d551e86da4e90c0d088e3/EnviroMonitorWeb/templates/rest_framework/api.html#L13)):*
<details><summary><i>Previously, lechup (Leszek Piątek) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/10)*

**Comment by lechup** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/10#-:-KZVu_iJ_pTaUf4O-JeG:bnfp4nl)*

**Comment by grillazz** [comment]
closes #7, closes #7

**Pull request merged**
