### PR TITLE
duplicated views removed and docs endpoint path fixed

### PR DESCRIPTION
**Pull request by grillazz**
This change is [Reviewable](https://reviewable.io/reviews/enviromonitor/enviromonitorweb/19)

### CODE REVIEW

**Comment by zen** [comment]
:lgtm:

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/19#-:-K_dRodo-buAqke67IUs:bg7igk9)*

**Comment by lechup** [comment]
Good work. :lgtm_strong: 

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/19#-:-K_dWBgY_UyYrW94TQGk:b-h442kx)*

**Comment by zen** [comment]
Ca someone look at the failing builds? I would start working on #20 but I need this to be merged first

**Comment by grillazz** [comment]
@zen build failing b/c we have no unit tests at all. I will add few today and build will be green./

**Pull request merged**
