### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by lechup**
* project folder structure cleanup
** docker dir
** settings
** removed redundant EnviroMonitorWeb folder
* docker postgis as default db backend instead of sqlite
* travis cleanup - we do not need to run on different python versions - we are using docker so we are using docker python

---
This change is [Reviewable](https://reviewable.io/reviews/enviromonitor/enviromonitorweb/23)

### CODE REVIEW

**Comment by lechup** [comment]
@ajakubo1 @grillazz @zen if You have 10 minutes take a look please...

**Comment by grillazz** [comment]
@lechup basic django project structure should looks like https://docs.djangoproject.com/en/1.10/intro/tutorial01/ - your changes are breaking this rule.

**Comment by grillazz** [comment]
@lechup what is purpose of implementing 'entry-point.sh' ? Our assumption was that docker will be only addon on dev level for ppl who wants to use docker...

**Comment by grillazz** [comment]
@lechup what is the purpose of moving changing `Dockerfile` from `FROM python:3.5` to `FROM ubuntu:16.04` ? Again >>  Our assumption was that docker will be only addon on dev level for ppl who wants to use docker... and this stuff is overcomplicating whole project to manage

**Comment by lechup** [comment]
@grillazz 

Regarding project structure, You are reffering this one?:

**Comment by lechup** [comment]
@grillazz 

Regarding entry point You are right.

I'll prepare fixes with using wait-for-it.sh + create separate repo with some postactivate and deactivate scripts with bash aliases - I'm just lasy and didn't want to type `docker-compose run web --rm python manage.py` each time ;)

**Comment by lechup** [comment]
@grillazz 

Regarding changing Dockerfile, I've tried to base it on `python:3.5-alpine`, but I had troubles to get postgis requirements there. Then I moved to ubuntu:16.04, because it is what I use on daily basis so I know how to deal with it. I've forgoten that python:3.5 is based on `jessie` that should have same packages names. I'll clean it up. Thanks!

**Comment by lechup** [comment]
@grillazz I've updated PR, and have such issues:
* if I do not wrap wait-for-it.sh + changing owner of files created by root docker user within entrypoint, only main cmd will support those features, so I've left entrypoint as a wrapper
* `python:3.5` is based on `jessie` which do not have `postgresql-9.5` packages I've changed postgis image to 9.4

**Comment by grillazz** [comment]
Reviewed 19 of 32 files at r1, 9 of 9 files at r2, 52 of 52 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/enviromonitor/enviromonitorweb/23)*

**Pull request merged**
